services:
  parser:
    build: .
    restart: on-failure
    environment:
      - KNOWDE_EMAIL=${KNOWDE_EMAIL}
      - KNOWDE_PASSWORD=${KNOWDE_PASSWORD}
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
    command: >
      bash -c "Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 & 
      python scripts/run_parser.py"

  api:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
    command: uvicorn src.api.api:app --host 0.0.0.0 --port 8000

  product_extractor:
    build: .
    restart: on-failure
    environment:
      - KNOWDE_EMAIL=${KNOWDE_EMAIL}
      - KNOWDE_PASSWORD=${KNOWDE_PASSWORD}
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
    command: >
      bash -c "Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 & 
      python scripts/extract_products.py"